### ISSUE TITLE
empty folders

### ISSUE THREAD

**Issue by Violetaye** [yangjenhao/BioLaySumm-2023-Task2-ReadabilityControlledSummarizationOfBiomedicalArticles#1]
Hello! Thank you for your sharing! Is this the complete code? I noticed that three folders are empty. Will they be uploaded later?

**Comment by yangjenhao** [comment]
Hi, 
Regarding the three empty folders:
1. The files in the "scientific_lay_summarisation" folder were downloaded from https://huggingface.co/datasets/tomasg25/scientific_lay_summarisation.
2. The "model" folder will store the models generated by model.py.
3. The "out" folder will hold the summaries predicted by eval.py. Alternatively, you can use the official evaluation tool (https://github.com/TGoldsack1/BioLaySumm2023-evaluation_scripts).
