### ISSUE TITLE
Inquiry about the source of the "data/test.jsonl" file in predict.py

### ISSUE THREAD

**Issue by Violetaye** [yangjenhao/BioLaySumm-2023-Task2-ReadabilityControlledSummarizationOfBiomedicalArticles#2]
I have been exploring your project and came across the predict.py script. I noticed that it references a file named "data/test.jsonl". I would like to inquire about the origin and creation process of this file. Could you kindly provide some insights or guidance on how to obtain or generate the "data/test.jsonl" file? Any information or instructions you can provide would be greatly appreciated.

**Comment by yangjenhao** [comment]
Hello,
You can obtain the generated summary files from `eval.py`. The file data/test.jsonl is an example used to test the generated summary files.
